export const userInputs = [
  {
    id: 1,
    label: "Name and surname",
    type: "text",
    placeholder: "Tunji Akande",
  },
  {
    id: 2,
    label: "Email",
    type: "email",
    placeholder: "tunji@gmail.com",
  },
  {
    id: 3,
    label: "Phone",
    type: "text",
    placeholder: "+1 234 34 5465",
  },
  {
    id: 4,
    label: "Password",
    type: "text",
    placeholder: "Tunji Akande",
  },
  {
    id: 5,
    label: "Address",
    type: "text",
    placeholder: "70 Washington Square,",
  },
  {
    id: 6,
    label: "Country",
    type: "text",
    placeholder: "USA",
  },
];

export const productInputs = [
  {
    id: 1,
    label: "Title",
    type: "text",
    placeholder: "Apple Macbook Pro",
  },
  {
    id: 2,
    label: "Description",
    type: "text",
    placeholder: "Description",
  },
  {
    id: 3,
    label: "Category",
    type: "text",
    placeholder: "Computers",
  },
  {
    id: 4,
    label: "Price",
    type: "text",
    placeholder: "100",
  },
  {
    id: 5,
    label: "Stock",
    type: "text",
    placeholder: "in stock",
  },
];





// export const productInputs = [
//   {
//     //_id: "1",
//     name: "Mapple Earphones",
//     slug: "Mapple-Earphones",
//     keygen: "Kid KD3569",
//     gender: "Female",
//     cat: ["Kids"],
//     size: ["XS", "S", "M", "L", "XL", "XXL"],
//     color: [
//       "fa-solid fa-circle  cl-1",
//       "fa-solid fa-circle  cl-2",
//       "fa-solid fa-circle  cl-3",
//       "fa-solid fa-circle  cl-4",
//       "fa-solid fa-circle  cl-5",
//       "fa-solid fa-circle  cl-6",
//       "fa-solid fa-circle  cl-7",
//     ],
//     price: 14.99,
//     countInStock: 0,
//     brand: ["Abercrombie &"],
//     image: "/imgs/kid1.png",
//     images: "",
//     productLikes: 1,
//     discount: "25",
//     rating: 3.0,
//     numReviews: 10,
//   },
//   {
//     //_id: "2",
//     name: "Mapple-Earphones",
//     slug: "Mapple Earphones-plug",
//     keygen: "Men BK3569",
//     gender: "Male",
//     cat: ["Men"],
//     size: ["XS", "S", "M", "L", "XL", "XXL"],
//     color: [
//       "fa-solid fa-circle  cl-1",
//       "fa-solid fa-circle  cl-2",
//       "fa-solid fa-circle  cl-3",
//       "fa-solid fa-circle  cl-4",
//       "fa-solid fa-circle  cl-5",
//       "fa-solid fa-circle  cl-6",
//       "fa-solid fa-circle  cl-7",
//     ],
//     price: 14.99,
//     countInStock: "20",
//     brand: "Fitch",
//     image: "/imgs/shirt1.png",
//     images: "",
//     productLikes: 1,
//     discount: "25",
//     rating: 4.0,
//     numReviews: 10,
//   },
//   {
//     //_id: "3",
//     name: "Women's Knitwear Offers",
//     slug: "Women's-Knitwear-Offers",
//     keygen: "Women WM3569",
//     gender: "Female",
//     cat: ["Women"],
//     size: ["XS", "S", "M", "L", "XL", "XXL"],
//     color: [
//       "fa-solid fa-circle  cl-1",
//       "fa-solid fa-circle  cl-2",
//       "fa-solid fa-circle  cl-3",
//       "fa-solid fa-circle  cl-4",
//       "fa-solid fa-circle  cl-5",
//       "fa-solid fa-circle  cl-6",
//       "fa-solid fa-circle  cl-7",
//     ],
//     price: 14.99,
//     countInStock: "20",
//     brand: "Adidas",
//     image: "/imgs/women1.png",
//     images: "",
//     productLikes: 1,
//     discount: "25",
//     rating: 3.0,
//     numReviews: 10,
//   },
//   {
//     //_id: "4",
//     name: "Men Casual Lizard",
//     slug: "Men-Casual-Lizard",
//     keygen: "Men BK3569",
//     gender: "Male",
//     cat: ["Men"],
//     size: ["XS", "S", "M", "L", "XL", "XXL"],
//     color: [
//       "fa-solid fa-circle  cl-1",
//       "fa-solid fa-circle  cl-2",
//       "fa-solid fa-circle  cl-3",
//       "fa-solid fa-circle  cl-4",
//       "fa-solid fa-circle  cl-5",
//       "fa-solid fa-circle  cl-6",
//       "fa-solid fa-circle  cl-7",
//     ],
//     price: 19.99,
//     countInStock: "20",
//     brand: "ASOS",
//     image: "/imgs/shirt2.png",
//     images: "",
//     productLikes: 1,
//     discount: "25",
//     rating: 4.5,
//     numReviews: 10,
//   },
//   {
//     //_id: "5",
//     name: "Harajuku Tshirt",
//     slug: "Harajuku-Tshirt",
//     keygen: "Kid KD3569",
//     gender: "Male",
//     cat: ["Kids"],
//     size: ["XS", "S", "M", "L", "XL", "XXL"],
//     color: [
//       "fa-solid fa-circle  cl-1",
//       "fa-solid fa-circle  cl-2",
//       "fa-solid fa-circle  cl-3",
//       "fa-solid fa-circle  cl-4",
//       "fa-solid fa-circle  cl-5",
//       "fa-solid fa-circle  cl-6",
//       "fa-solid fa-circle  cl-7",
//     ],
//     price: 14.99,
//     countInStock: "20",
//     brand: "Cheap Monday",
//     image: "/imgs/kid2.png",
//     images: "",
//     productLikes: 1,
//     discount: "25",
//     rating: 5.0,
//     numReviews: 10,
//   },
//   {
//     //_id: "6",
//     name: "Women Casual Lizard",
//     slug: "Women-Casual-Lizard",
//     keygen: "Women WM3569",
//     gender: "Female",
//     cat: ["Women"],
//     size: ["XS", "S", "M", "L", "XL", "XXL"],
//     color: [
//       "fa-solid fa-circle  cl-1",
//       "fa-solid fa-circle  cl-2",
//       "fa-solid fa-circle  cl-3",
//       "fa-solid fa-circle  cl-4",
//       "fa-solid fa-circle  cl-5",
//       "fa-solid fa-circle  cl-6",
//       "fa-solid fa-circle  cl-7",
//     ],
//     price: 19.99,
//     countInStock: "20",
//     brand: ["Abercrombie &"],
//     image: "/imgs/women2.png",
//     images: "",
//     productLikes: 1,
//     discount: "25",
//     rating: 3.0,
//     numReviews: 10,
//   },
//   {
//     //_id: "7",
//     name: "Novelty T-Shirts",
//     slug: "Novelty-T-Shirts",
//     keygen: "Men BK3569",
//     gender: "Male",
//     cat: ["Men"],
//     size: ["XS", "S", "M", "L", "XL", "XXL"],
//     color: [
//       "fa-solid fa-circle  cl-1",
//       "fa-solid fa-circle  cl-2",
//       "fa-solid fa-circle  cl-3",
//       "fa-solid fa-circle  cl-4",
//       "fa-solid fa-circle  cl-5",
//       "fa-solid fa-circle  cl-6",
//       "fa-solid fa-circle  cl-7",
//     ],
//     price: 12.09,
//     countInStock: "20",
//     brand: ["Abercrombie &"],
//     image: "/imgs/shirt3.png",
//     images: "",
//     productLikes: 1,
//     discount: "25",
//     rating: 4.0,
//     numReviews: 10,
//   },
//   {
//     //_id: "8",
//     name: "Novelty Dress",
//     slug: "Novelty-Dress",
//     keygen: "Women WM3569",
//     gender: "Female",
//     cat: ["Women"],
//     size: ["XS", "S", "M", "L", "XL", "XXL"],
//     color: [
//       "fa-solid fa-circle  cl-1",
//       "fa-solid fa-circle  cl-2",
//       "fa-solid fa-circle  cl-3",
//       "fa-solid fa-circle  cl-4",
//       "fa-solid fa-circle  cl-5",
//       "fa-solid fa-circle  cl-6",
//       "fa-solid fa-circle  cl-7",
//     ],
//     price: 12.09,
//     countInStock: "20",
//     brand: ["Abercrombie &"],
//     image: "/imgs/women3.png",
//     images: "",
//     productLikes: 1,
//     discount: "25",
//     rating: 5.0,
//     numReviews: 10,
//   },
//   {
//     //_id: "9",
//     name: "Various T-Shorts",
//     slug: "Various-T-Shorts",
//     keygen: "Men BK3569",
//     gender: "Male",
//     cat: ["Men"],
//     size: ["XS", "S", "M", "L", "XL", "XXL"],
//     color: [
//       "fa-solid fa-circle  cl-1",
//       "fa-solid fa-circle  cl-2",
//       "fa-solid fa-circle  cl-3",
//       "fa-solid fa-circle  cl-4",
//       "fa-solid fa-circle  cl-5",
//       "fa-solid fa-circle  cl-6",
//       "fa-solid fa-circle  cl-7",
//     ],
//     price: 24.99,
//     countInStock: "20",
//     brand: ["Abercrombie &"],
//     image: "/imgs/shirt4.png",
//     images: "",
//     productLikes: 1,
//     discount: "25",
//     rating: 4.0,
//     numReviews: 10,
//   },
// ];
